# fly.toml app configuration file generated for rasa-project-floral-grass-8269 on 2024-11-18T14:37:41-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rasa-project-floral-grass-8269'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 5005
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  internal_port = 5060
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 5060
